### ISSUE TITLE
getting error on packages get

### ISSUE THREAD

**Issue by fralways** [OpenFlutter/flutter_image_compress#54]
Since I'm using beta flutter build I'm using dependency you provided but is showing an error. Any idea how to fix it?

```
Git error. Command: git rev-list --max-count=1 173ce7d73835ce35f695ac859bdabf471d1160e6

fatal: bad object 173ce7d73835ce35f695ac859bdabf471d1160e6

```

```
flutter_image_compress:
    git:
      url: https://github.com/OpenFlutter/flutter_image_compress.git
      ref: 173ce7d73835ce35f695ac859bdabf471d1160e6
```
