### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by chornbe** [OpenFlutter/flutter_image_compress#73]
Flutter v 1.8.1
Kotlin v 1.3.41
Android Studio v 3.4.2
Mac OS 10.14.5

What other info should I provide to help determine what's causing the following error...? Thanks

Running flutter build apk --release emits the following information:

admins-MBP:diary_app_flutter chris$ flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0.9s
Resolving dependencies...                                           9.5s
Note: /Users/chris/development/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+1/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
e: /Users/chris/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.2/android/src/main/kotlin/com/example/flutterimagecompress/FlutterImageCompressPlugin.kt: (25, 76): Type mismatch: inferred type is Activity! but AppCompatActivity was expected
e: /Users/chris/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.2/android/src/main/kotlin/com/example/flutterimagecompress/FlutterImageCompressPlugin.kt: (26, 76): Type mismatch: inferred type is Activity! but AppCompatActivity was expected
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      82.4s
Gradle task assembleRelease failed with exit code 1

Here's the dependency list from my flutter project yaml file:
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.2+1
  connectivity: 0.4.3+1
  flutter_launcher_icons: "^0.7.0"
  package_info: ^0.4.0+3
  intl: ^0.15.8
  palette_generator: ^0.1.1
  uuid: ^2.0.1
  image_picker: ^0.4.10
  camera: ^0.4.2
  flutter_image_compress: ^0.6.2
  # image_gallery_saver: ^1.1.0

```
